#???????????????????????
server:
  port: 8089
#??mysql?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test0_mysql?serverTimezone=GMT%2b8 #??mysql url
#    username: root  #?????????
#    password: 123456  #????????
    username: root #?????????
    password: root #????????
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl